function X = Pej_integral3(dx, D1L, D1H, D2L, D2H,D3L, D3H, RelativeTol, BreakPoint)
SymmetricDomain = all(BreakPoint == mean([D1L, D1H; D2L, D2H; D3L, D3H],2)); % Matlab's multidimenstional integrators work very fast on symmetric domains

if SymmetricDomain
    X = integral3(dx, D1L, D1H, D2L, D2H,D3L, D3H,'AbsTol', 0, 'RelTol', RelativeTol);
else
    BrP = BreakPoint;
    EPS = 0.001;
    X = ...
        integral3(dx, D1L      , BrP, D2L      , BrP, D3L      , BrP,'AbsTol', 0, 'RelTol', RelativeTol) + ...
        integral3(dx, BrP + EPS, D1H, D2L      , BrP, D3L      , BrP,'AbsTol', 0, 'RelTol', RelativeTol) + ...
        integral3(dx, D1L      , BrP, BrP + EPS, D2H, D3L      , BrP,'AbsTol', 0, 'RelTol', RelativeTol) + ...
        integral3(dx, BrP + EPS, D1H, BrP + EPS, D2H, D3L      , BrP,'AbsTol', 0, 'RelTol', RelativeTol) + ...
        integral3(dx, D1L      , BrP, D2L      , BrP, BrP + EPS, D3H,'AbsTol', 0, 'RelTol', RelativeTol) + ...
        integral3(dx, BrP + EPS, D1H, D2L      , BrP, BrP + EPS, D3H,'AbsTol', 0, 'RelTol', RelativeTol) + ...
        integral3(dx, D1L      , BrP, BrP + EPS, D2H, BrP + EPS, D3H,'AbsTol', 0, 'RelTol', RelativeTol) + ...
        integral3(dx, BrP + EPS, D1H, BrP + EPS, D2H, BrP + EPS, D3H,'AbsTol', 0, 'RelTol', RelativeTol) ;
end
end